// Package http — SPA static serving (v2.5.0+).
//
// Backend embeds the production React build (dist/) into the Go binary and
// serves it on any non-API path so that any device on LAN can open
// http://<касса-ip>:3001 in a browser and get the full UI without Electron.
//
// Build pipeline:
//
//	vite build                                 → ./dist
//	cp -r ../dist server/internal/transport/http/spa
//	go build ./cmd/restos-server               → spa/ baked into binary
//
// Repo only tracks spa/.gitkeep + spa/index.html (placeholder) — real assets
// are gitignored and regenerated by the CI step. See Makefile `embed-spa`.
package http

import (
	"embed"
	"io/fs"
	"net/http"
	"strings"
)

//go:embed all:spa
var spaFS embed.FS

// SPAHandler returns an http.Handler that serves the embedded React SPA.
//
// Behaviour:
//   - /api/*, /sse, /healthz, /readyz, /docs — explicit 404 (router should
//     have matched these earlier; defensive guard against accidental masking).
//   - Existing static file inside spa/ — served with default Content-Type
//     detection and no-cache for index.html.
//   - Anything else — fallback to index.html (BrowserRouter / HashRouter
//     friendly: F5 on /operations/pos still loads the SPA shell).
func SPAHandler() http.Handler {
	sub, err := fs.Sub(spaFS, "spa")
	if err != nil {
		return http.NotFoundHandler()
	}
	fileServer := http.FileServer(http.FS(sub))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		p := r.URL.Path

		// Defensive guards — never shadow API/SSE/health.
		// НЕ блокируем /docs — там статические шаблоны импорта
		// (spa/docs/шаблон-*.xlsx). Swagger UI на /docs не зарегистрирован.
		// Раньше guard «HasPrefix(p, "/docs")» 404'ил скачивание шаблонов.
		if strings.HasPrefix(p, "/api/") ||
			strings.HasPrefix(p, "/sse") ||
			p == "/healthz" || p == "/readyz" {
			http.NotFound(w, r)
			return
		}

		// Strip leading slash for fs.Open semantics.
		clean := strings.TrimPrefix(p, "/")
		if clean == "" {
			clean = "index.html"
		}

		f, err := sub.Open(clean)
		if err == nil {
			_ = f.Close()
			// index.html — no-cache (для атомарных деплоев новой версии).
			if clean == "index.html" || strings.HasSuffix(clean, "/index.html") {
				w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
			}
			fileServer.ServeHTTP(w, r)
			return
		}

		// SPA fallback — отдаём index.html на любой не-найденный путь.
		w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
		r2 := r.Clone(r.Context())
		r2.URL.Path = "/"
		fileServer.ServeHTTP(w, r2)
	})
}
